# Generated by Django 3.2 on 2023-08-06 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='docfiles/')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='imgfile/')),
            ],
        ),
        migrations.CreateModel(
            name='PastQuestionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('year_inserted', models.IntegerField()),
                ('regular_field', models.CharField(max_length=100)),
                ('back_field', models.CharField(max_length=100)),
                ('author_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pastquestionupload',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='pastquestionupload',
            name='images',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='PastQuestionUpload',
        ),
        migrations.AddField(
            model_name='imagefile',
            name='past_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blogapp.pastquestiondocument'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='past_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='blogapp.pastquestiondocument'),
        ),
    ]
